config/routes.rb
Dareme::Application.routes.draw do

  resources :authentications

    mount Ckeditor::Engine => '/ckeditor'
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
    resources :events  
  

    root :to => "events#index"

    resources :profiles, :only => [:update, :edit] 

    resources :videos, :only => [:edit, :new]
          
    resources :comments, :only => [:destroy, :create]

    resources :followings, only: [:destroy, :create]
  
    devise_for :users    
    devise_scope :user do 
      resources :users, only: [:show]
    end

  match '/auth/:provider/callback' => 'authentications#create'

    

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #Associations
  	belongs_to :user, :inverse_of => :profile

  #Attributes
  	attr_accessible :about, :first_name, :last_name, :user_id,  :image, :remote_image_url,
      :updated_at, :created_at, :image_cache, :remove_image
    mount_uploader :image, ImageUploader

  #Validation
    validates :first_name, :presence => true
    validates :last_name, :presence => true
    validates :user_id, :presence => true

  #Functions
  def full_name=(fullname)
      first,last = fullname.split(' ')  # or some smarter way to split
      self.first_name = first
      self.surname = last
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  
  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to current_user, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  
  <div class="field">
    <%= f.label :about %><br />
    <%= f.cktext_area :about, :input_html => { 
          :cols => 10, :rows => 30}  %>
  </div>
<br />
<br />

<h3>Profile Photo </h3>
  <div class="field">
    <%= f.file_field :image %>
  </div>  
    <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_show.html.erb
<p id="notice"><%= notice %></p>
<h1>Profile</h1>

<% if current_user.id == profile.user_id then %>
  <%= link_to 'Edit', edit_profile_path(profile) %> 
<% else %>
  <% if @following.nil? %>
    <%= link_to 'Follow Me!', followings_path, method: :post %> 
  <% else %>
    <%= link_to 'Stop Following Me!', @following, method: :delete, data: { confirm: 'Are you sure?' } %> 
  <% end %>
<% end %>
<br />
Profile Image<br/>
<%= image_tag profile.image_url(:thumb_200) %>
<br />
<p>
  <b>First name:</b>
  <%= profile.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= profile.last_name %>
</p>

<p>
  <b>User:</b>
  <%= profile.user_id %>
</p>

<p>
  <b>User Name:</b>
  <%= current_user.slug %>
</p>

<p>
  <b>About:</b>
  <%= profile.about.html_safe if not profile.about.nil? %>
</p>
<br />

<h1>Events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Event Date</th>
    <th>Location</th>
    <th>Bidding End</th>
  </tr>

<% events.each do |event| %>
  <tr>
    <td><%= link_to event.title, event %></td>
    <td><%= event.event_time %></td>
    <td><%= event.location %></td>
    <td><%= event.raise_end %></td>
  </tr>
<% end %>
</table>

<br />

<h1>Comments </h1>
<%= render "/comments/show_comments", :comments => comments %>
<% if current_user.followed_users.exists?(@user) then %>
  <%= render '/comments/form' %>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>