config/routes.rb
Dareme::Application.routes.draw do

  resources :authentications

    mount Ckeditor::Engine => '/ckeditor'
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
    resources :events  
  

    root :to => "events#index"

    resources :profiles, :only => [:update, :edit] 

    resources :videos, :only => [:edit, :new]
          
    resources :comments, :only => [:destroy, :create]

    resources :followings, only: [:destroy, :create]
  
    devise_for :users    
    devise_scope :user do 
      resources :users, only: [:show]
    end

  match '/auth/:provider/callback' => 'authentications#create'

    

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  #Associations
  	belongs_to :user, inverse_of: :authentications

  #Attributes
  	attr_accessible :provider, :uid, :user_id, :nickname, :token

  #Scopes
  	scope :youtube, where(:provider => 'youtube')
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = current_user.authentications if current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authentications }
    end
  end


  # POST /authentications
  # POST /authentications.json
  def create
    omniauth = request.env["omniauth.auth"]



    #puts omniauth.to_yaml

    
    a = current_user.authentications.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if a.nil?
      current_user.authentications.create(provider: omniauth.provider, uid: omniauth.uid, nickname: omniauth.info.nickname, token: omniauth.credentials.token)
    end

    flash[:notice] = "Authentication successful."
    redirect_to authentications_url    
  end


  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy

    respond_to do |format|
      format.html { redirect_to authentications_url }
      format.json { head :no_content }
    end
  end

  def oauth_failure
    puts params.inspect
    flash[:notice] = "There was an error authenticating with your account"
    redirect_to authentications_url
  end

end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider.titleize %></div>
          <div class="uid"><%= authentication.nickname %></div>
          <%= link_to "X", authentication, data: {:confirm => 'Are you sure you want to remove this authentication option?'}, :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/youtube" class="auth_provider">
  <%= image_tag "youtube_64.png", :size => "64x64", :alt => "YouTube" %>
  YoutTube
</a>
<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>
<a href="/auth/google_oauth2" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  Google
</a>
<a href="/auth/open_id" class="auth_provider">
  <%= image_tag "openid_64.png", :size => "64x64", :alt => "OpenID" %>
  OpenID
</a>
<div class="clear"></div>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>